---
title: "Untitled"
format: html
editor: source
---

```{r}
#| label: pull ACS data

# Metadata for American Community Survey Poverty table (among multiple options): 
#   https://pearson.socialexplorer.com/data/ACS2022/metadata/?ds=ACS22&table=B14006
ma_pov <- 
  get_acs( 
    geography = "tract", 
    variables = c("B14006_001", "B14006_002"),
    state = "MA", 
    year = 2022,
    geometry = TRUE,
    output = "wide",
  ) %>% 
  rename(all_n = B14006_001E,
         pov_n = B14006_002E) %>% 
  select(GEOID, all_n, pov_n)

```

```{r}
#| label: source and compare school district geographies to district names in teacher data

# Pull Massachusetts school district geographies from the Census TIGER service
elem_sds <- tigris::school_districts(state = "MA", cb = TRUE, type = 'elementary')
secd_sds <- tigris::school_districts(state = "MA", cb = TRUE, type = 'secondary')
unif_sds <- tigris::school_districts(state = "MA", cb = TRUE, type = 'unified')

ma_sds <- 
  bind_rows(elem_sds %>% mutate(level = "elementary"), 
            secd_sds %>% mutate(level = "secondary"), 
            unif_sds %>% mutate(level = "unified"))

# Load teacher data
load("data/ma_ed.Rda")

# Compare school districts in shape file to teacher data
cbind(ma_sds$NAME      %>% sort() %>% head(20), 
      ma_ed$distr_name %>% sort() %>% unique() %>% head(20))
```

```{r}
#| label: iteratively clean and compare district names

ma_sds <- 
  ma_sds %>% 
  mutate(distr_name_forcomp = 
           NAME %>% 
           str_replace("(Regional)? School District", "") %>% 
           str_trim() %>% 
           str_to_lower())

ma_ed_formerge <- 
  ma_ed %>% 
  mutate(distr_name_forcomp =
           distr_name %>% 
           str_replace_all("\\(District\\)", "") %>% 
           str_replace_all("(Regional|Charter) School District", "") %>% 
           str_replace_all("Regional$", "") %>% 
           str_trim() %>% 
           str_to_lower())

### Assess status of cleaning
  
# Calculate matches
ma_sds_match <- ma_sds$distr_name_forcomp %in% ma_ed_formerge$distr_name_forcomp
# What percent match?
mean(ma_sds_match)
# Which don't match?
non_matches <- ma_sds$distr_name_forcomp[!ma_sds_match]
print(non_matches)

# Some code to interactively investigate
str_subset(ma_sds$distr_name_forcomp, paste(non_matches, collapse = "|"))
str_subset(unique(ma_ed_formerge$distr_name_forcomp), paste(non_matches, collapse = "|"))


```

```{r}
#| label: generate a mapping between tracts and school districts for aggregation

# First ensure that the poverty data and school districts have the same 
# coordinate reference system
st_crs(ma_pov) <- st_crs(ma_sds)

# Generate the intersection of tracts and school districts
# Note: this operation creates a row for every unique overlap of geography, as
# if cutting stained glass based on the overlap of multiple layers
tr_sd_intersect <- st_intersection(ma_pov, ma_sds)

# Calculate the size of overlap to identify small parts of tracts that do not
# merit maintaining
tr_sd_xwalk <- 
  tr_sd_intersect %>% 
  mutate(area = st_area(tr_sd_intersect)) %>% 
  mutate(pct_tract_in_sd = area / sum(area),
          .by = GEOID) %>% 
  filter(as.numeric(pct_tract_in_sd) > 0.1) %>% 
  # recalculate percentages
  mutate(pct_tract_in_sd = area / sum(area),
          .by = GEOID) %>% 
  select(GEOID, distr_name_forcomp, pct_tract_in_sd)

```

```{r}
#| label: aggregate poverty data to school district level

ma_pov_distr <- 
  ma_pov %>% 
  as.data.frame() %>% 
  merge(tr_sd_xwalk,
        by = "GEOID") %>% 
  summarize(all_n = sum(all_n),
            pov_n = sum(pov_n),
            .by = distr_name_forcomp) %>% 
  mutate(pov_pct = pov_n / all_n)

# Examine distribution of poverty
ggplot(ma_pov_distr %>% sample_n(20),
       aes(x = reorder(distr_name_forcomp, pov_pct),
           y = pov_pct,
           fill = pov_pct)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = percent) + 
  labs(title = "Poverty Rate for a Random Sample of Districts",
       x = "",
       y = "") +
  theme(axis.text.x = element_text(angle = 90,
                                   hjust = 1,
                                   vjust = 0.5),
        legend.position = "none")
  
```

```{r}
#| label: save output

save(ma_pov_distr, ma_sds, ma_ed_formerge,
     file = "data/geo_data.Rda")
```

